### ISSUE TITLE
Develop Canonical List of Input Data

### ISSUE THREAD

**Issue by gidden** [openclimatedata/openscm#96] opened 2019-02-06 10:20 UTC
We should develop such a list that IAMs can provide, specifically, this will need to enumerate:

- gas species
- sectors
- regions/spatial dimensions

Once we have a complete list, we can better inform efforts to generate such data from existing IAM timeseries (likely as a separate project/repo since it does not seem to fit in either `pyam` or `openscm` at the moment).

@znicholls @rgieseke @chrisroadmap @swillner maybe we can start with gas species? Could we make a super set of those used as input to MAGICC, FAIR, HECTOR, etc?

**Comment by rgieseke** [comment] 2019-02-06 10:42
I got annoyed with the slightly differing ghg names in SCMs so i once build `ghgrenamer`

https://github.com/openclimatedata/ghgrenamer

It does some regex-ing and these replacements:
https://github.com/openclimatedata/ghgrenamer/blob/master/names.yaml

**Comment by gidden** [comment] 2019-02-06 11:23
Awesome! This is a great start =)

**Comment by swillner** [comment] 2019-02-08 15:54
Related to #22

**Comment by swillner** [comment] 2019-02-13 14:00
Closed as a duplicate of #22

**Closed by swillner** 2019-02-13 14:00 UTC
Labels: discussion, docs, duplicate, enhancement
